### ISSUE TITLE
Login geht nicht

### ISSUE THREAD

**Issue by ma4mo** [Janokisu/AnrufHinweis#2]
Ich nutze Linux, firefox 96.0.2 (64-Bit) und das ADDon  geht nicht
![Login-schlägt-fehl](https://user-images.githubusercontent.com/80324600/151798496-d81c87bd-5100-4903-b666-f65dbe2616a2.png)
ldet:

**Comment by Janokisu** [comment]
Ist bei deiner FritzBox TR-064 aktiviert?
(oh, ich sehe gerade, dass in der Hilfe zwar der Punkt da ist, aber nicht die Anleitung dazu)

https://avm.de/service/wissensdatenbank/dok/FRITZ-Box-7590/3266_MyFRITZ-App-fur-Android-einrichten/
-> FRITZ!Box für Zugriff von Anwendungen einrichten

**Comment by Janokisu** [comment]
Fix mit V. 0.2.0
