### ISSUE TITLE
tel-Links

### ISSUE THREAD

**Issue by ErikKrause** [Janokisu/AnrufHinweis#4]
Super wäre, wenn die Extension beim Klick auf einen Tel-Link die Nummer über die Fritz!Box wählen könnte.
Siehe auch https://wiki.selfhtml.org/wiki/HTML/Tutorials/Links/klickbare_Telefonnummern

**Comment by Janokisu** [comment]
gute Idee 👍
Kommt mit dem nächsten Update

**Comment by Janokisu** [comment]
In V. 0.2.0 eingebaut.
